version: "2"
services:
  cliente:
    build: ./Cliente
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  gateway:
    build: ./Gateway
    ports:
     - "5010:5000"
    volumes:
     - .:/code
  suma:
    build: ./Suma
    ports:
     - "5020:5000"
    volumes:
     - .:/code

  resta:
    build: ./Resta
    ports:
     - "5030:5000"
    volumes:
     - .:/code
  multiplicacion:
    build: ./Multiplicacion
    ports:
     - "5040:5000"
    volumes:
     - .:/code
  division:
    build: ./Division
    ports:
     - "5050:5000"
    volumes:
     - .:/code

 
