gateway:
  build: ./Gateway
  ports:
   - "5000:5000"
  volumes:
   - .:/code
suma:
  build: ./Suma
  ports:
   - "4000:5000"
  volumes:
   - .:/code

resta:
  build: ./Resta
  ports:
   - "3000:5000"
  volumes:
   - .:/code
multiplicacion:
  build: ./Multiplicacion
  ports:
   - "2000:5000"
  volumes:
   - .:/code
division:
  build: ./Division
  ports:
   - "1000:5000"
  volumes:
   - .:/code

 
